version: "3.9"

services:
  frontend:
    image: naveenkumar1137/sampledev:${DOCKER_IMAGE_TAG:-dev-latest}
    container_name: lv360_sampledev_frontend

    restart: always

    ports:
      - "4030:4030"

    env_file:
      - .env.dev

    networks:
      - lv360-shared-network

    healthcheck:
      test: [ "CMD", "wget", "--spider", "--tries=1", "http://localhost:4030" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  lv360-shared-network:
    external: true
