services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4020:4020"
    environment:
      - PUBLIC_NEXT_NODE_ENV=development
    networks:
      - app-network

    healthcheck:
      test: [ "CMD", "wget", "--spider", "--tries=1", "http://localhost:4020" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge
