export const FILTER_VI = {
  "Full-time": "Toàn thời gian",
  Remote: "Từ xa",
  "Part-time": "Bán thời gian",
  Contract: "Hợp đồng",
  Internship: "Thực tập",
};

export const JOBS = [
  { id: 1, title: "Senior Backend Engineer", titleVi: "Kỹ sư Backend Cao cấp", company: "ABC Technologies", verified: true, location: "Ho Chi Minh City", locationVi: "TP. Hồ Chí Minh", salary: "25M – 40M VND", type: "Full-time", mode: "Remote", modeVi: "Từ xa", level: "Senior", levelVi: "Cấp cao", industry: "Technology", industryVi: "Công nghệ", posted: "2 days ago", postedVi: "2 ngày trước", skills: ["Node.js", "PostgreSQL", "AWS", "Microservices"] },
  { id: 2, title: "Digital Marketing Specialist", titleVi: "Chuyên viên Marketing Số", company: "Sen Vang Group", verified: true, location: "Hanoi", locationVi: "Hà Nội", salary: "15M – 22M VND", type: "Full-time", mode: "On-site", modeVi: "Tại văn phòng", level: "Mid-level", levelVi: "Trung cấp", industry: "Retail & Commerce", industryVi: "Bán lẻ & Thương mại", posted: "1 day ago", postedVi: "1 ngày trước", skills: ["SEO", "Google Ads", "Content", "Analytics"] },
  { id: 3, title: "Product Designer (UI/UX)", titleVi: "Thiết kế Sản phẩm (UI/UX)", company: "Minh Long Digital", verified: true, location: "Da Nang", locationVi: "Đà Nẵng", salary: "18M – 28M VND", type: "Full-time", mode: "Hybrid", modeVi: "Kết hợp", level: "Mid-level", levelVi: "Trung cấp", industry: "Media & Creative", industryVi: "Truyền thông & Sáng tạo", posted: "3 days ago", postedVi: "3 ngày trước", skills: ["Figma", "Design systems", "Prototyping", "User research"] },
  { id: 4, title: "HR Specialist", titleVi: "Chuyên viên Nhân sự", company: "Phuong Nam Logistics", verified: false, location: "Ho Chi Minh City", locationVi: "TP. Hồ Chí Minh", salary: "12M – 18M VND", type: "Part-time", mode: "On-site", modeVi: "Tại văn phòng", level: "Mid-level", levelVi: "Trung cấp", industry: "Transport & Logistics", industryVi: "Vận tải & Logistics", posted: "5 days ago", postedVi: "5 ngày trước", skills: ["Recruitment", "Onboarding", "Labour law"] },
  { id: 5, title: "General Accountant", titleVi: "Kế toán Tổng hợp", company: "Dai Duong Viet", verified: true, location: "Hai Phong", locationVi: "Hải Phòng", salary: "10M – 15M VND", type: "Contract", mode: "On-site", modeVi: "Tại văn phòng", level: "Mid-level", levelVi: "Trung cấp", industry: "Transport & Logistics", industryVi: "Vận tải & Logistics", posted: "1 week ago", postedVi: "1 tuần trước", skills: ["VAS", "Tax reporting", "Excel"] },
  { id: 6, title: "Data Analyst Intern", titleVi: "Thực tập sinh Phân tích Dữ liệu", company: "ABC Technologies", verified: true, location: "Ho Chi Minh City", locationVi: "TP. Hồ Chí Minh", salary: "4M – 6M VND", type: "Internship", mode: "Hybrid", modeVi: "Kết hợp", level: "Entry-level", levelVi: "Mới bắt đầu", industry: "Technology", industryVi: "Công nghệ", posted: "4 days ago", postedVi: "4 ngày trước", skills: ["SQL", "Python", "Power BI"] },
  { id: 7, title: "Frontend Engineer (React)", titleVi: "Kỹ sư Frontend (React)", company: "Nhat Tin Software", verified: true, location: "Hanoi", locationVi: "Hà Nội", salary: "20M – 32M VND", type: "Full-time", mode: "Remote", modeVi: "Từ xa", level: "Mid-level", levelVi: "Trung cấp", industry: "Technology", industryVi: "Công nghệ", posted: "6 hours ago", postedVi: "6 giờ trước", skills: ["React", "TypeScript", "CSS", "Testing"] },
  { id: 8, title: "Customer Success Manager", titleVi: "Quản lý Thành công Khách hàng", company: "Sen Vang Group", verified: true, location: "Ho Chi Minh City", locationVi: "TP. Hồ Chí Minh", salary: "22M – 30M VND", type: "Full-time", mode: "Hybrid", modeVi: "Kết hợp", level: "Senior", levelVi: "Cấp cao", industry: "Retail & Commerce", industryVi: "Bán lẻ & Thương mại", posted: "2 days ago", postedVi: "2 ngày trước", skills: ["Account management", "SaaS", "Reporting"] },
  { id: 9, title: "Mechanical Engineer", titleVi: "Kỹ sư Cơ khí", company: "Truong Thanh Manufacturing", verified: true, location: "Binh Duong", locationVi: "Bình Dương", salary: "16M – 24M VND", type: "Full-time", mode: "On-site", modeVi: "Tại văn phòng", level: "Mid-level", levelVi: "Trung cấp", industry: "Manufacturing", industryVi: "Sản xuất", posted: "1 week ago", postedVi: "1 tuần trước", skills: ["AutoCAD", "SolidWorks", "QA"] },
  { id: 10, title: "Content Writer (Bilingual)", titleVi: "Chuyên viên Nội dung (Song ngữ)", company: "Minh Long Digital", verified: true, location: "Remote — Vietnam", locationVi: "Từ xa — Việt Nam", salary: "12M – 20M VND", type: "Contract", mode: "Remote", modeVi: "Từ xa", level: "Mid-level", levelVi: "Trung cấp", industry: "Media & Creative", industryVi: "Truyền thông & Sáng tạo", posted: "3 days ago", postedVi: "3 ngày trước", skills: ["Copywriting", "EN/VI", "SEO"] },
  { id: 11, title: "DevOps Engineer", titleVi: "Kỹ sư DevOps", company: "Nhat Tin Software", verified: true, location: "Ho Chi Minh City", locationVi: "TP. Hồ Chí Minh", salary: "30M – 45M VND", type: "Full-time", mode: "Hybrid", modeVi: "Kết hợp", level: "Senior", levelVi: "Cấp cao", industry: "Technology", industryVi: "Công nghệ", posted: "1 day ago", postedVi: "1 ngày trước", skills: ["Kubernetes", "Terraform", "CI/CD", "Observability"] },
  { id: 12, title: "Sales Executive", titleVi: "Chuyên viên Kinh doanh", company: "Phuong Nam Logistics", verified: false, location: "Can Tho", locationVi: "Cần Thơ", salary: "10M – 25M VND", type: "Full-time", mode: "On-site", modeVi: "Tại văn phòng", level: "Entry-level", levelVi: "Mới bắt đầu", industry: "Transport & Logistics", industryVi: "Vận tải & Logistics", posted: "4 days ago", postedVi: "4 ngày trước", skills: ["B2B sales", "Negotiation", "CRM"] },
];

export const COMPANIES = [
  { id: 1, name: "ABC Technologies", industry: "Technology", industryVi: "Công nghệ", location: "Ho Chi Minh City", locationVi: "TP. Hồ Chí Minh", openJobs: 12, verified: true },
  { id: 2, name: "Sen Vang Group", industry: "Retail & Commerce", industryVi: "Bán lẻ & Thương mại", location: "Hanoi", locationVi: "Hà Nội", openJobs: 7, verified: true },
  { id: 3, name: "Minh Long Digital", industry: "Media & Creative", industryVi: "Truyền thông & Sáng tạo", location: "Da Nang", locationVi: "Đà Nẵng", openJobs: 5, verified: true },
  { id: 4, name: "Dai Duong Viet", industry: "Transport & Logistics", industryVi: "Vận tải & Logistics", location: "Hai Phong", locationVi: "Hải Phòng", openJobs: 9, verified: true },
  { id: 5, name: "Nhat Tin Software", industry: "Technology", industryVi: "Công nghệ", location: "Hanoi", locationVi: "Hà Nội", openJobs: 14, verified: true },
  { id: 6, name: "Truong Thanh Manufacturing", industry: "Manufacturing", industryVi: "Sản xuất", location: "Binh Duong", locationVi: "Bình Dương", openJobs: 6, verified: true },
  { id: 7, name: "Phuong Nam Logistics", industry: "Transport & Logistics", industryVi: "Vận tải & Logistics", location: "Can Tho", locationVi: "Cần Thơ", openJobs: 4, verified: false },
  { id: 8, name: "Hoa Binh Finance", industry: "Finance & Banking", industryVi: "Tài chính & Ngân hàng", location: "Ho Chi Minh City", locationVi: "TP. Hồ Chí Minh", openJobs: 8, verified: true },
];

export const RESOURCES = [
  { cat: ["Hồ sơ", "Profile"], title: ["Xây dựng hồ sơ nổi bật với nhà tuyển dụng", "Build a profile recruiters notice"], desc: ["Cách trình bày kinh nghiệm, kỹ năng và thành tích để hồ sơ của bạn dễ đọc và dễ so khớp.", "How to present experience, skills and achievements so your profile is easy to read and easy to match."], read: ["6 phút đọc", "6 min read"] },
  { cat: ["Phỏng vấn", "Interviews"], title: ["Chuẩn bị cho vòng phỏng vấn đầu tiên", "Preparing for a first-round interview"], desc: ["Những câu hỏi thường gặp và cách cấu trúc câu trả lời của bạn theo tình huống cụ thể.", "Common questions and how to structure your answers around concrete situations."], read: ["8 phút đọc", "8 min read"] },
  { cat: ["Lương", "Salary"], title: ["Thảo luận về mức lương một cách chuyên nghiệp", "Discussing salary professionally"], desc: ["Cách nghiên cứu mức lương thị trường và trao đổi kỳ vọng của bạn một cách rõ ràng.", "How to research market ranges and communicate your expectations clearly."], read: ["5 phút đọc", "5 min read"] },
  { cat: ["Ứng tuyển", "Applying"], title: ["Viết thư ứng tuyển ngắn và hiệu quả", "Writing a short, effective cover note"], desc: ["Một ghi chú ngắn gọn giải thích lý do bạn phù hợp thường hiệu quả hơn một lá thư dài.", "A brief note explaining why you fit usually works better than a long letter."], read: ["4 phút đọc", "4 min read"] },
  { cat: ["Nghề nghiệp", "Career"], title: ["Chuyển đổi ngành nghề: bắt đầu từ đâu", "Changing industries: where to start"], desc: ["Xác định kỹ năng có thể chuyển đổi và cách trình bày chúng cho một lĩnh vực mới.", "Identify transferable skills and how to frame them for a new field."], read: ["7 phút đọc", "7 min read"] },
  { cat: ["Từ xa", "Remote"], title: ["Làm việc từ xa hiệu quả tại Việt Nam", "Working remotely, effectively"], desc: ["Thiết lập thói quen, giao tiếp và kỳ vọng khi làm việc từ xa hoặc kết hợp.", "Setting routines, communication and expectations in remote or hybrid roles."], read: ["6 phút đọc", "6 min read"] },
];
